# The Site Settings
# v2.0
# https://github.com/cotes2020/jekyll-theme-chirpy
# © 2017-2019 Cotes Chung
# MIT licensed

theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Additional parameters for datetime localization, optional. › https://github.com/iamkun/dayjs/tree/dev/src/locale
prefer_datetime_locale:

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Europe/Paris

title: Xavier Mignot # the main title

tagline: Azure, IaC & other things # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  Xavier Mignot's blog about Azure, GitHub, Terraform, Bicep, IaC and IoT

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: 'https://blog.xmi.fr'

author: Xavier Mignot # change to your full name

github:
  username: xaviermignot # change to your github username

twitter:
  username: _xavierm # change to your twitter username

social:
  name: Xavier Mignot # it will shows as the copyright owner in Footer
  email: contact@xmi.fr # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://www.linkedin.com/in/mignotxavier
    - https://twitter.com/_xavierm # change to your twitter homepage
    - https://github.com/xaviermignot # change to your github homepage
    - https://hachyderm.io/@xavierm

plugins:
  - jekyll-link-attributes

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn: ''

# the avatar on sidebar, support local or CORS resources

avatar: /assets/img/avatar.png?n=n #the ?n=n is a workaround to fix a 404 bug on the avatar

# boolean type, the global switch for ToC in posts.
toc: true

comments:
  active: giscus        # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # Giscus options › https://giscus.app
  giscus:
    repo: xaviermignot/xaviermignot.github.io             # <gh-username>/<repo>
    repo_id: MDEwOlJlcG9zaXRvcnkzMzI0MzM4NDY=
    category: General
    category_id: DIC_kwDOE9CJts4CUIYT

paginate: 10

assets:
  self_host:
    enabled: true

pwa:
  enabled: true   # the option for PWA feature

counter:
  enabled: true
  data-id: 2d107d40-555c-48d3-8ee3-bd4388e8fa84

external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude:
    - https://hachyderm.io/@xavierm


# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: '' # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ''
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - '*.gem'
  - '*.gemspec'
  - tools
  - docs
  - README.md
  - LICENSE
  - gulpfile.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
